apiVersion: v1
kind: Service
metadata:
  name: apiclima
  namespace: apiclima
  labels:
    app: apiclima
spec:
  selector:
    app: apiclima
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

